# Generated by Django 4.2.30 on 2026-04-20 22:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('generated', 'Generiert'), ('reviewed', 'Geprüft'), ('sent', 'Versendet')], default='draft', max_length=20)),
                ('weather', models.CharField(blank=True, max_length=100)),
                ('temperature', models.SmallIntegerField(blank=True, null=True)),
                ('raw_input_text', models.TextField()),
                ('input_language', models.CharField(default='de', max_length=5)),
                ('structured_data', models.JSONField(default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=64)),
                ('ai_tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tagesbericht',
                'verbose_name_plural': 'Tagesberichte',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('work_performed', 'Ausgeführte Arbeiten'), ('materials_used', 'Verwendetes Material'), ('equipment', 'Geräte/Maschinen'), ('personnel', 'Personal'), ('obstacle', 'Behinderungen/Probleme'), ('safety', 'Sicherheit'), ('note', 'Sonstige Notizen')], max_length=30)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('content', models.TextField()),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reports.dailyreport')),
            ],
            options={
                'verbose_name': 'Berichtseintrag',
                'verbose_name_plural': 'Berichtseinträge',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('project_number', models.CharField(blank=True, max_length=64)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='reports.dailyreport')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-Mail-Versand',
                'verbose_name_plural': 'E-Mail-Versände',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.project'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'is_active'], name='reports_pro_company_38e012_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['company', 'report_date'], name='reports_dai_company_04aa66_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['created_by', 'status'], name='reports_dai_created_a49a8b_idx'),
        ),
    ]
